# Generated by Django 5.1.2 on 2024-11-04 05:55

import files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=files.storage.CloudinaryStorage, upload_to='documents/'),
        ),
    ]
